-- JAY FUENTES AND MATT REFSNIDER

-- START DROP STATEMENTS

-- DROP ALL TABLES

DROP TABLE VEHICLES_CI CASCADE CONSTRAINTS;
DROP TABLE BILL_TOS_CI CASCADE CONSTRAINTS;
DROP TABLE ITEMS_CI CASCADE CONSTRAINTS;
DROP TABLE OWNERS_CI CASCADE CONSTRAINTS;
DROP TABLE INVOICES_CI CASCADE CONSTRAINTS;
DROP TABLE ITEMS_SOLD_CI CASCADE CONSTRAINTS;

-- DROP ALL SEQUENCES

DROP SEQUENCE BILL_TOS_BILL_TO_NO_SEQ;
DROP SEQUENCE ITEMS_ITEM_NO_SEQ;
DROP SEQUENCE INVOICES_INVOICE_NO_SEQ;

-- END DROP STATEMENTS



s


sfd
asdf
