-- CREATE SEQUENCES

CREATE SEQUENCE bill_tos_bill_to_no_seq
	START WITH 8923
	INCREMENT BY 1
	MAXVALUE 99999
	NOCYCLE
	NOCACHE;

CREATE SEQUENCE items_item_no_seq 
	START WITH 1122334455 
	INCREMENT BY 1 
	MAXVALUE 9999999999 
	NOCYCLE 
	NOCACHE; 

CREATE SEQUENCE invoices_invoice_no_seq
	START WITH 25333 
	INCREMENT BY 1 
	MAXVALUE 99999 
	NOCYCLE
	NOCACHE; 

-- TO GET INFORMATION ABOUT SEQUENCES

SELECT sequence_name, increment_by 
FROM user_sequences;
